In [2]:
import pandas as pd

df = pd.read_csv("books_bandwidth.tsv", sep='\t')
df.head()

   RI  BOOK_ID     AQ  BANDWIDTH COMMENT
0  92     6973  clean      17657     NaN
1  92     7967  clean      17140     NaN
2  92     9288  clean      17312     NaN
3  92     9783  clean      16709     NaN
4  92    10425  clean      17915     NaN

In [3]:
len(df)

77

In [5]:
(df.RI.astype(str) + '_' + df.AQ).unique()

array(['92_clean', '6097_clean', '6097_other', '6670_other', '6671_other',
       '8051_other', '9017_clean', '9136_other', '11614_other',
       '11697_other', '12787_other'], dtype=object)

In [6]:
df.BANDWIDTH.describe()

count       77.000000
mean     16091.766234
std       1754.283149
min      13264.000000
25%      14298.000000
50%      16451.000000
75%      17312.000000
max      19638.000000
Name: BANDWIDTH, dtype: float64

In [7]:
df[df.AQ=="other"].head()

      RI  BOOK_ID     AQ  BANDWIDTH                   COMMENT
17  6097    15114  other      14987  The speaker is artistic.
18  6097    15793  other      16795  The speaker is artistic.
19  6670     6416  other      14556                       NaN
20  6670     7476  other      14211                       NaN
21  6670     7908  other      14211                       NaN

In [18]:
df[(df.BANDWIDTH==df.BANDWIDTH.max())|(df.BANDWIDTH==df.BANDWIDTH.min())]

       RI  BOOK_ID     AQ  BANDWIDTH COMMENT
58  11614    11736  other      13264     NaN
60  11614    11965  other      13264     NaN
72  12787    13871  other      19638     NaN

In [15]:
df[~df.COMMENT.isna()].head(50)

,RI,BOOK_ID,AQ,BANDWIDTH,COMMENT
7,6097,8992,clean,16365,This book sounds a bit different than the rest...
8,6097,9575,clean,16451,The speaker is artistic.
9,6097,11271,clean,16623,The speaker is artistic.
10,6097,13418,clean,16623,The speaker is artistic.
11,6097,13657,clean,16882,The speaker is artistic.
12,6097,14411,clean,17312,The speaker is artistic.
13,6097,14764,clean,16968,The speaker is artistic.
14,6097,14843,clean,16968,The speaker is artistic.
15,6097,15277,clean,18518,The speaker is artistic.
16,6097,15326,clean,16882,The speaker is artistic.
17,6097,15114,other,14987,The speaker is artistic.
18,6097,15793,other,16795,The speaker is artistic.
45,8051,8930,other,15245,This book was moved to the `other` set due to ...
46,8051,9685,other,14814,This book was moved to the `other` set due to ...
47,8051,14468,other,14814,This book was moved to the `other` set due to ...
48,9017,11216,clean,15417,The speaker is artistic.
49,9017,13089,clean,17054,Slightly stronger attenuation in high frequenc...
50,9017,13130,clean,16365,Slightly stronger attenuation in high frequenc...
51,9017,13885,clean,16882,The speaker is artistic.
52,9017,14261,clean,16451,The speaker is artistic.
53,9017,15482,clean,19293,The speaker is artistic.
54,9017,15752,clean,19379,The speaker is artistic.

In [23]:
len(df), len(df[df.BANDWIDTH>=16000])

(77, 42)

In [20]:
len(df), len(df[(df.BANDWIDTH>=16000)&(df.COMMENT.isna())])

(77, 25)

In [21]:
len(df), len(df[(df.BANDWIDTH>=15500)&(df.COMMENT.isna())])

(77, 28)

In [22]:
len(df), len(df[(df.BANDWIDTH>=15000)&(df.COMMENT.isna())])

(77, 31)